### ISSUE TITLE
CPP syntax error

### ISSUE THREAD

**Issue by bkbncn** [honza/vim-snippets#1448]
Hi

After  #1446 , got error from  ultisnips,

`Invalid line 'priority 2' in ~/.vim/bundle/vim-snippets/snippets/cpp.snippets:1`

**Comment by smjonas** [comment]
Snippet priorities are only supported by UltiSnips snippets, so they should not be used for snippets in the snippets directory @amarakon

**Comment by amarakon** [comment]
> Snippet priorities are only supported by UltiSnips snippets, so they should not be used for snippets in the snippets directory @amarakon

Oh, I did not know that. I tried with nvim-snippy and it worked for me. Is there a way to check if `priority` is supported and change the priority of it is? Or is there another way to redefine a snippet without using `priority`? See #1445.

**Comment by smjonas** [comment]
I think some snippet engines like nvim-snippy and LuaSnip support priorities in SnipMate snippets although it's not part of the official spec. 

I found this:
https://github.com/garbas/vim-snipmate/blob/525f331320427bf7aeb07651e2536b1f8a23df03/doc/SnipMate.txt#L266

Can you test if adding a ! to the snippet definition works for you?

**Comment by amarakon** [comment]
Putting a `!` to the snippet definition does not work with nvim-snippy or LuaSnip. But it probably works with SnipMate. But interestingly, if you are using LuaSnip, you do not need to specify the priority so you can just redefine a snippet. With nvim-snippy though, you need to specify the priority to redefine a snippet.

I think the solution here will be to just remove the `priority` line from the `snippets` file so nobody will have any errors. Do not accept my latest pull request (#1447) yet because it also uses `priority`.

**Comment by bkbncn** [comment]
After latest #1447, it's good now, thank you
