### ISSUE TITLE
C snippets do not follow the same style.

### ISSUE THREAD

**Issue by chavezgu** [honza/vim-snippets#559]
The snippets in the snippets/ folder have a slightly different style that the ones in UltiSnipts, regarding the curly brace. The former have the open curly brace on the same line as the "for" or "if" statement, while the later have it below the line.

**Comment by lpil** [comment]
Thank you for this issue. This is clearly not ideal.

Which style is dominant in the C community? How do we decide which to adopt?

**Comment by AssailantLF** [comment]
I feel like the K&R style (open brace on the same line) are used more often, just because of the popularity and history of the book, not to mention the linux kernel coding standard. However, it would fit better with the popular plugin vim-surround to use the Allman style, since that's how it surrounds lines of code (open brace on its own line).

It's really tough since the differences are almost entirely aesthetic and trivial. I personally vote for the Allman style. If only there were some way to have a compromise. :/

**Comment by chavezgu** [comment]
I would personally vote for the K&R style, for the same reasons @AssailantLF said. However, I was
just pointing out that is not ideal to have two different styles for the same language. Right now engines using "UltiSnips" folder use the K&R style meanwhile the "snippets" folder use the Allman.

I also agree that the differences are trivial, but I think right now we have the worst of both worlds by having both styles.

**Comment by SirVer** [comment]
+1 for K&R style.

**Comment by jalcine** [comment]
Since #562 is closed, wouldn't that close this issue? Just curious.

**Comment by SirVer** [comment]
yup, I agree.
