### ISSUE TITLE
Why is there difference between these two versions?

### ISSUE THREAD

**Issue by agauniyal** [honza/vim-snippets#657]
1.  (vim-snippets/snippets/cpp.snippets)[https://github.com/honza/vim-snippets/blob/master/snippets/cpp.snippets]
2. ( vim-snippets/UltiSnips/cpp.snippets)[https://github.com/honza/vim-snippets/blob/master/UltiSnips/cpp.snippets]

Are 1st one, Ultisnips exclusive? Which directory should I point to in
 ```let g:UltiSnipsSnippetsDir="~/.vim/plugged/vim-snippets/........"``` ?

**Comment by fuadsaud** [comment]
I'm also curious about the distinction. Some of the snippets under `UltiSnips/` differ significantly from the ones under `snippets/`.

**Comment by lpil** [comment]
In theory all snippets are to be in the snipmate format by default, and only ones that use special ultisnips features are to be written in that format.

This is generally not the case though, due to this project's history of being two different projects that merged. Most the languages have not been cleaned up to remove duplication after this event.

If you're using a package manager for vim you shouldn't need to specify a directory to use.

**Comment by fuadsaud** [comment]
Hmm, I see. I'll try to do some cleanup on the snippets I use.

**Comment by lpil** [comment]
Pull requests always welcome :)

**Comment by agauniyal** [comment]
So if I'm adding new snippets for cpp, which one should I add to?

**Comment by lpil** [comment]
The the snipmate format. :)

**Comment by agauniyal** [comment]
@lpil or @fuadsaud  just one more thing,

```
##
## Class
# class
snippet cl
	class ${1:`vim_snippets#Filename('$1', 'name')`}
	{
	public:
		$1(${2});
		~$1();

	private:
		${0:/* data */}
	};

##
## Access Modifiers
# private
snippet pri
	private
```

is this some kind of syntax or rule for snipmate snippets to not use line breaks b/w rules and sometimes double `##`'s and sometime single `#`? Do they provide some kind of scope or just that initial author had chose to do this way?

**Comment by lpil** [comment]
It's purely a stylistic choice as far as I'm aware.
