### ISSUE TITLE
How to disable sets of snippets?

### ISSUE THREAD

**Issue by Industrial** [honza/vim-snippets#681]
Hi!

Since I got the snippet list working, it will help me a lot in actually using the snippets. My problem is that there are a lot of snippets that I really don't care for that are in the list of 336 (!) snippets for JavaScript.

One example is the jquery snippets. I don't really care for them so I'd rather not see them in the list and not use them. Is it possible to disable certain sets of snippets?

**Comment by honza** [comment]
I think this might be better answered by the actual snippet engine project. :sparkles:

**Comment by ajzafar** [comment]
I can only speak for SnipMate, but personally I'm more interested in giving users good tools to organize their snippets appropriately, rather than to provide tools for fixing any organizational issues that may arise. (Having said that there is some support for removing snippets in SnipMate of course.) However I think these tools are misunderstood or not documented as well as they should be---or maybe both. In terms of the JQuery snippets for example, this repo has them at `snippets/javascript/javascript-jquery.snippets`. SnipMate, at least, follows Vim's procedures for loading snippet files based on scope names, and until Vim changes I have no plans to change  SnipMate in this regard. For the scope `javascript`, the following files are loaded, where `dir` is an entry in `'runtimepath'` and `*` is a wildcard.

- `dir/javascript.snippets`
- `dir/javascript_*.snippets`
- `dir/javascript/*.snippets`

Additionally, SnipMate provides the `:SnipMateLoadScope` command to add a buffer-local scope alias (and I know UltiSnips provides a similar command). At least part of the intention for the command was to allow snippets to be loaded on an as needed basis, via something like

    if " this file can be detected to contain JQuery
        SnipMateLoadScope jquery
    endif

which then loads `jquery` snippets in the same fashion as `javascript` snippets were loaded above.

If these aren't enough, then please open up an issue/PR on garbas/vim-snipmate with some suggestions.

**Comment by codeinabox** [comment]
How would I do this in UltiSnips? I've grepped the documentation for references to remove and disable but can't see how this is done.

**Comment by winkee01** [comment]
Take an example, If I don't want several snippets provided in your `c.snippets`, how can I disable it so that when I type the keyword, it won't be shown or triggered?
